app:
  name: "bluebell"
  port: 8080
  version: "1.0.0"
  machine_id: 1           # 机器ID
  start_time: "2006-01-02" 

log:
  level: "debug"          
  filename: "bluebell.log" 
  max_size: 200           #MB
  max_age: 30             #天
  max_backups: 7          #文件数


mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "lll279912138+1S" 
  dbname: "bluebell"
  max_open_conns: 20   # 最大打开连接数
  max_idle_conns: 10   # 最大空闲连接数

auth:
  jwt_expire: 24